esphome:
  name: ble-am43
  platformio_options:
    board_build.cmake_extra_args: >-
      -DCMAKE_C_COMPILER_LAUNCHER=ccache
      -DCMAKE_CXX_COMPILER_LAUNCHER=ccache
host:
logger:
external_components:
  - source: {type: local, path: ../components}
esp32_ble_tracker:
ble_client:
  - mac_address: 02:00:00:00:00:01
    id: blind
cover:
  - platform: am43
    ble_client_id: blind
    name: "Blind"
    pin: 8888
sensor:
  - platform: am43
    ble_client_id: blind
    battery_level:
      name: "Blind Battery"
    illuminance:
      name: "Blind Light"
